export const FEED_POSTS = [
  {
    id: 1,
    author: 'lamnv_dev',
    initial: 'L',
    avatarBg: '#dbe1ff',
    avatarColor: '#004ac6',
    meta: '5 giờ trước • CLB JS Club',
    title: 'Workshop: Làm chủ React cho dự án thực tế tại campus Hòa Lạc',
    excerpt:
      'Thứ 7 tuần này CLB mình có tổ chức buổi workshop nhỏ tại phòng 204 tòa Alpha. Bạn nào quan tâm đến React và muốn nâng cao kỹ năng frontend thì đăng ký tham gia nhé!',
    body: [
      'Thứ 7 tuần này CLB mình có tổ chức buổi workshop nhỏ tại phòng 204 tòa Alpha. Bạn nào quan tâm đến React và muốn nâng cao kỹ năng frontend thì đăng ký tham gia nhé!',
      'Buổi workshop sẽ tập trung vào các pattern thực tế khi làm việc với React trong dự án: quản lý state, tối ưu render, tổ chức component và tích hợp API.',
      'Thời gian: 14:00 – 17:00 | Địa điểm: Phòng 204, tòa Alpha. Số lượng có hạn, đăng ký qua form trong bài hoặc inbox CLB JS Club.',
    ],
    tags: ['Sự kiện', 'ReactJS'],
    semester: 6,
    major: 'SE',
    likes: 42,
    comments: 8,
    views: '1.2k',
    commentList: [
      {
        id: 'c1',
        author: 'minh_se_22',
        initial: 'M',
        avatarBg: '#ffe4e6',
        avatarColor: '#be123c',
        meta: '2 giờ trước',
        content: 'Workshop này có cần đăng ký trước không bạn?',
        likes: 3,
      },
      {
        id: 'c2',
        author: 'tngo282999',
        initial: 'T',
        avatarBg: '#dbe1ff',
        avatarColor: '#004ac6',
        meta: '1 giờ trước',
        content: 'Mình tham gia buổi trước rồi, mentor hướng dẫn rất chi tiết. Nên đi sớm để có chỗ ngồi nhé!',
        likes: 5,
      },
    ],
  },
  {
    id: 2,
    author: 'khanh_fpt_se',
    initial: 'K',
    avatarBg: '#d6e3ff',
    avatarColor: '#515f78',
    meta: '2 giờ trước • Chuyên ngành SE',
    title: 'Kinh nghiệm chọn nhóm Capstone Project 1 cho kỳ tới?',
    excerpt:
      'Chào mọi người, mình sắp lên kỳ 7 và đang lo lắng về việc chọn nhóm làm đồ án. Nên chọn nhóm dựa trên sở thích cá nhân hay kỹ năng thực tế của mỗi người hơn?',
    body: [
      'Chào mọi người, mình sắp lên kỳ 7 và đang lo lắng về việc chọn nhóm làm đồ án. Nên chọn nhóm dựa trên sở thích cá nhân hay kỹ năng thực tế của mỗi người hơn?',
      'Theo kinh nghiệm của mình, nên cân bằng cả hai: chọn bạn có cùng mục tiêu điểm số và bổ sung kỹ năng cho nhau (ví dụ: 1 người giỏi backend, 1 người giỏi frontend, 1 người giỏi viết tài liệu).',
      'Ai đi trước cho mình xin ít review với! Mình đang phân vân giữa 2 nhóm ở lớp SE1701.',
    ],
    tags: ['Capstone', 'Kinh nghiệm'],
    semester: 7,
    major: 'SE',
    likes: 24,
    comments: 12,
    views: '450',
    commentList: [
      {
        id: 'c3',
        author: 'phatnguyentan2205',
        initial: 'P',
        avatarBg: '#dcfce7',
        avatarColor: '#15803d',
        meta: '45 phút trước',
        content: 'Mình recommend chọn theo kỹ năng hơn, đỡ stress khi chia task.',
        likes: 2,
      },
    ],
  },
  {
    id: 3,
    author: 'minh_se_22',
    initial: 'M',
    avatarBg: '#ffe4e6',
    avatarColor: '#be123c',
    meta: '8 giờ trước • CLB Java',
    title: 'Share source code mẫu Spring Boot REST API cho đồ án môn SWR302',
    excerpt:
      'Mình vừa push repo mẫu có sẵn auth JWT, pagination và validation. Ai cần tham khảo cho assignment tuần này thì comment để mình gửi link nhé.',
    body: [
      'Mình vừa push repo mẫu có sẵn auth JWT, pagination và validation. Ai cần tham khảo cho assignment tuần này thì comment để mình gửi link nhé!',
      'Repo gồm: layer controller/service/repository, DTO mapping, exception handler và unit test cơ bản.',
    ],
    tags: ['Spring Boot', 'SWR302'],
    semester: 6,
    major: 'SE',
    likes: 67,
    comments: 15,
    views: '890',
    commentList: [],
  },
  {
    id: 4,
    author: 'tngo282999',
    initial: 'T',
    avatarBg: '#dbe1ff',
    avatarColor: '#004ac6',
    meta: '1 ngày trước • Cộng đồng SE',
    title: 'Tips ôn thi PRF192: Làm sao để nhớ được logic vòng lặp và mảng?',
    excerpt:
      'Mình từng fail môn này lần đầu vì chỉ học thuộc code. Sau khi đổi cách luyện tập theo flowchart thì điểm tăng rõ rệt.',
    body: [
      'Mình từng fail môn này lần đầu vì chỉ học thuộc code. Sau khi đổi cách luyện tập theo flowchart thì điểm tăng rõ rệt.',
      'Gợi ý: vẽ sơ đồ trước khi code, luyện 3 bài/ngày trên Edunext và note lại pattern hay gặp.',
    ],
    tags: ['PRF192', 'Tips học tập'],
    semester: 6,
    major: 'SE',
    likes: 31,
    comments: 9,
    views: '620',
    commentList: [],
  },
  {
    id: 5,
    author: 'phatnguyentan2205',
    initial: 'P',
    avatarBg: '#dcfce7',
    avatarColor: '#15803d',
    meta: '1 ngày trước • CLB AI',
    title: 'Demo chatbot hỗ trợ tra cứu đề thi bằng RAG — feedback welcome!',
    excerpt:
      'Team mình build prototype cho Capstone: upload PDF đề cũ, hỏi đáp theo ngữ cảnh. Ai muốn test thử bản beta thì inbox.',
    body: [
      'Team mình build prototype cho Capstone: upload PDF đề cũ, hỏi đáp theo ngữ cảnh. Ai muốn test thử bản beta thì inbox.',
      'Stack: Python, LangChain, ChromaDB, FastAPI. Đang tối ưu độ chính xác câu trả lời cho môn DBI202.',
    ],
    tags: ['AI', 'Capstone'],
    semester: 7,
    major: 'AI',
    likes: 88,
    comments: 21,
    views: '2.1k',
    commentList: [],
  },
  {
    id: 6,
    author: 'hong_phuoc_it',
    initial: 'H',
    avatarBg: '#fef3c7',
    avatarColor: '#b45309',
    meta: '2 ngày trước • CLB Mobile',
    title: 'Flutter vs React Native cho đồ án mobile — nên chọn gì năm 2026?',
    excerpt:
      'Nhóm mình đang phân vân tech stack cho mobile app quản lý lịch học. Có ai từng deploy production bằng Flutter hoặc RN không?',
    body: [
      'Nhóm mình đang phân vân tech stack cho mobile app quản lý lịch học. Có ai từng deploy production bằng Flutter hoặc RN không?',
      'Tiêu chí: thời gian học, performance, dễ tìm tài liệu và khả năng tích hợp API từ backend Spring.',
    ],
    tags: ['Mobile', 'Thảo luận'],
    semester: 7,
    major: 'SE',
    likes: 19,
    comments: 14,
    views: '380',
    commentList: [],
  },
  {
    id: 7,
    author: 'chi_thong_dev',
    initial: 'C',
    avatarBg: '#e0e7ff',
    avatarColor: '#4338ca',
    meta: '2 ngày trước • CLB JS Club',
    title: 'Recap buổi chia sẻ về TypeScript strict mode và best practices',
    excerpt:
      'Slide và recording buổi talk tối qua đã upload lên drive CLB. Tóm tắt nhanh: bật strict, dùng union type thay any.',
    body: [
      'Slide và recording buổi talk tối qua đã upload lên drive CLB. Tóm tắt nhanh: bật strict, dùng union type thay any.',
      'Link drive gửi trong group Discord CLB JS. Buổi sau sẽ nói về testing với Vitest.',
    ],
    tags: ['TypeScript', 'Sự kiện'],
    semester: 6,
    major: 'SE',
    likes: 53,
    comments: 6,
    views: '710',
    commentList: [],
  },
  {
    id: 8,
    author: 'kim_khoa_ai',
    initial: 'K',
    avatarBg: '#fce7f3',
    avatarColor: '#be185d',
    meta: '3 ngày trước • Chuyên ngành AI',
    title: 'Dataset mẫu cho bài lab Machine Learning tuần 4 — đã clean sẵn',
    excerpt:
      'Mình xử lý missing value và chuẩn hóa feature giúp team. File CSV + notebook EDA đính kèm trong comment.',
    body: [
      'Mình xử lý missing value và chuẩn hóa feature giúp team. File CSV + notebook EDA đính kèm trong comment.',
      'Lưu ý: nhớ split train/test trước khi scale để tránh data leakage nhé các bạn.',
    ],
    tags: ['Machine Learning', 'AI'],
    semester: 5,
    major: 'AI',
    likes: 41,
    comments: 11,
    views: '540',
    commentList: [],
  },
  {
    id: 9,
    author: 'anhpika',
    initial: 'A',
    avatarBg: '#ede9fe',
    avatarColor: '#6d28d9',
    meta: '3 ngày trước • Cộng đồng SE',
    title: 'Checklist chuẩn bị thực tập kỳ hè cho sinh viên năm 3',
    excerpt:
      'Tổng hợp CV, portfolio GitHub, LinkedIn và các câu hỏi phỏng vấn thường gặp. Hy vọng giúp các bạn apply internship dễ hơn.',
    body: [
      'Tổng hợp CV, portfolio GitHub, LinkedIn và các câu hỏi phỏng vấn thường gặp. Hy vọng giúp các bạn apply internship dễ hơn.',
      'Mình recommend có ít nhất 2 project có README rõ ràng và demo deploy được.',
    ],
    tags: ['Thực tập', 'Career'],
    semester: 6,
    major: 'SE',
    likes: 102,
    comments: 28,
    views: '3.4k',
    commentList: [],
  },
  {
    id: 10,
    author: 'ftes_member',
    initial: 'F',
    avatarBg: '#cffafe',
    avatarColor: '#0e7490',
    meta: '4 ngày trước • FTES',
    title: 'Mở đăng ký mentor 1-1 hỗ trợ ôn thi môn SWP391',
    excerpt:
      'Chương trình mentor miễn phí của FTES mở slot tuần này. Mỗi bạn được 2 buổi review requirement và diagram.',
    body: [
      'Chương trình mentor miễn phí của FTES mở slot tuần này. Mỗi bạn được 2 buổi review requirement và diagram.',
      'Đăng ký qua form trong bài. Ưu tiên nhóm chưa có mentor và deadline gần.',
    ],
    tags: ['SWP391', 'Mentor'],
    semester: 8,
    major: 'SE',
    likes: 76,
    comments: 18,
    views: '1.8k',
    commentList: [],
  },
]

export const TRENDING_POSTS = [
  'Top 5 công cụ AI nên dùng: Bí quyết bứt phá cho Dân IT 2025',
  'Hành trình học tập ấn tượng của Kim Khoa',
  'Từ mông lung đến bứt phá cùng AI: Hành trình của Hồng Phúc',
  'Vượt qua nỗi "Hoang mang đại học" cùng FTES',
  'Hành trình chạm đến Top 5 sinh viên xuất sắc của Chí Thông',
]

export function getPostById(id) {
  const numericId = Number(id)
  if (Number.isNaN(numericId)) return null
  return FEED_POSTS.find((post) => post.id === numericId) ?? null
}
